In [3]:
import numpy as np
from tensorflow.keras.layers import Dense, ReLU, BatchNormalization

In [4]:
X = np.random.randint(20,2000,(10,1))
X

array([[ 149],
       [1653],
       [ 231],
       [1422],
       [1037],
       [ 166],
       [1173],
       [1161],
       [ 449],
       [ 863]], dtype=int32)

In [6]:
dense_layer = Dense(1, activation=None, input_shape=(1,))
b_n_layer = BatchNormalization()
relu_layer = ReLU()

C:\Program Files\Python311\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
dense_output = dense_layer(X)
b_n_output = b_n_layer(dense_output)
relu_output = relu_layer(b_n_output)
output

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [ ]:
dense_output = Dense(1, activation=None, input_shape=(1,))(X)
b_n_output = BatchNormalization()(dense_output)
output = ReLU()(b_n_output)

In [8]:
dense_layer.weights

[<Variable path=dense/kernel, shape=(1, 1), dtype=float32, value=[[-1.5736412]]>,
 <Variable path=dense/bias, shape=(1,), dtype=float32, value=[0.]>]

In [27]:
dense_weights = np.array([[0.6826221], [0.02151406]])
dense_bias =np.array( [0.])

dense_weights, dense_bias

((2, 1), array([0.]))

In [26]:
X

(1, 2)

In [28]:
np.maximum(0, X @ dense_weights + dense_bias)

array([[7.2565022]])